language: php

php:
  - 7.0
  - 7.1
  - 7.2

matrix:
  fast_finish: true

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - js/forum/node_modules
    - js/admin/node_modules

before_install:
  - phpenv config-rm xdebug.ini || true

install:
  - composer install
  - cd $TRAVIS_BUILD_DIR/js/forum && npm install && npm run build
  - cd $TRAVIS_BUILD_DIR/js/admin && npm install && npm run build

script:
  - cd $TRAVIS_BUILD_DIR && vendor/bin/phpunit

after_success:
  - npm install @alrra/travis-scripts@^3.0.1
  - |
    # Set up SSH environment
    $(npm bin)/set-up-ssh \
      --key "$encrypted_678139e2bc67_key" \
      --iv "$encrypted_678139e2bc67_iv" \
      --path-encrypted-key "./.deploy.enc"

    # Commit bundle changes generated in before_script step
    # --commands is a weird no-op but required for commit-changes to run
    $(npm bin)/commit-changes \
      --commands "echo committing" \
      --commit-message "Bundled output for commit $TRAVIS_COMMIT [skip ci]" \
      --branch "webpack"

notifications:
  email:
    on_failure: change

env:
  global:
    # Define GH_USER_EMAIL & GH_USER_NAME env variables used by travis-scripts package
    secure: "DKgAHm0ulqQPSS8C0eJ1xBlcwEUzUuWyOZLrgBH/lHT9OsND64ComVjJ9JGLGl38BynNgNRsvB5+xjj8JdoivZvJNz6b7Xg14FIXmpszF2ZzBuENva8TKYcKnziqDl0tbvivD61SlnIKX4URJZr5cTKcg88l3hEUSEK+2HJSFhI="
    secure: "R7yEwlEAjPHUdFtj6PGWRsPFEIHWbhdpCQLcv0WuiD7jI5Xep/xzoMwLoM8DfreaVAAJImKXxauIshsWccUHKBeaxS1TIjEWrIvg5xCLpJK8/TUBj1/lo6HPwu6uV6H1ZD1mQULdpqJlKsu+fjXojkC7L7wDe86Bw9e78OwmwwY="