language: php

php:
  - 7.0
  - 7.1
  - 7.2

matrix:
  fast_finish: true

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - js/forum/node_modules
    - js/admin/node_modules

before_install:
  - phpenv config-rm xdebug.ini || true

install:
  - composer install

script:
  - vendor/bin/phpunit

jobs:
  include:
    - stage: bundle
      install:
        - cd $TRAVIS_BUILD_DIR/js/forum && npm install && npm run build
        - cd $TRAVIS_BUILD_DIR/js/admin && npm install && npm run build
        - cd $TRAVIS_BUILD_DIR && npm install @alrra/travis-scripts@^3.0.1
      script: |
        # Set up SSH environment
        $(npm bin)/set-up-ssh \
          --key "$encrypted_678139e2bc67_key" \
          --iv "$encrypted_678139e2bc67_iv" \
          --path-encrypted-key "./.deploy.enc"

        # Commit bundle changes generated in before_script step
        # --commands is a weird no-op but required for commit-changes to run
        $(npm bin)/commit-changes \
          --commands "echo committing" \
          --commit-message "Bundled output for commit $TRAVIS_COMMIT [skip ci]" \
          --branch "webpack"

notifications:
  email:
    on_failure: change

env:
  global:
    # Define GH_USER_EMAIL & GH_USER_NAME env variables used by travis-scripts package
    secure: "NsqM7pjwecsBddmMZZdWFfS/wAi7oXT3nlq7sNWpF6kKSGqicdPKIeT/QQrxiUZi/+yqJeLhP518T2DCSPoL6I/vSYBNv1Bu63UYckvW84ZSDFqJ1Or9b1zVpGwOnE8FS4+a/N0Tj3vnkIWNmi47SSEApLW49Hz6fH28L5fWN1A="
