language: php

php:
  - 7.0
  - 7.1
  - 7.2

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm
    - js/forum/node_modules
    - js/admin/node_modules

before_install:
  - phpenv config-rm xdebug.ini || true

install:
  - composer install

script:
  - vendor/bin/phpunit

jobs:
  include:
    # Add a job to bundle and commit Flarum's JavaScript
    - language: generic
      php: 
      before_install: 
      install:
        - cd $TRAVIS_BUILD_DIR/js/forum && npm install && npm run build
        - cd $TRAVIS_BUILD_DIR/js/admin && npm install && npm run build
      script: 
      after_success:
        - cd $TRAVIS_BUILD_DIR && npm install @alrra/travis-scripts@^3.0.1
        - $(npm bin)/set-up-ssh --key "$encrypted_678139e2bc67_key" --iv "$encrypted_678139e2bc67_iv" --path-encrypted-key "./.deploy.enc"
        - $(npm bin)/commit-changes --commands "true" --commit-message "Bundled output for commit $TRAVIS_COMMIT [skip ci]" --branch "master"

env:
  global:
    # Define GH_USER_EMAIL & GH_USER_NAME env variables used by travis-scripts package
    secure: "NsqM7pjwecsBddmMZZdWFfS/wAi7oXT3nlq7sNWpF6kKSGqicdPKIeT/QQrxiUZi/+yqJeLhP518T2DCSPoL6I/vSYBNv1Bu63UYckvW84ZSDFqJ1Or9b1zVpGwOnE8FS4+a/N0Tj3vnkIWNmi47SSEApLW49Hz6fH28L5fWN1A="
